name: CI

on:
  push:
    paths:
      - "**.java"
      - "pom.xml"
      - ".github/**"
  pull_request:
    paths:
      - "*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Cache maven build
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        uses: xlui/action-maven-cli/jdk8@master
        with:
          args: -B clean jacoco:prepare-agent package --file pom.xml jacoco:report sonar:sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Show Error Logs
        if: failure()
        run: |
          cat hs_err_pid*
          rm hs_err_pid*

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Generate build number
        uses: einaregilsson/build-number@v2
        with:
          token: ${{secrets.github_token}}

      - name: Print build number
        run: echo "Build number is $BUILD_NUMBER"

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Cache maven build
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Apply build number
        run: |
          sed -i "s|<version>dev_build</version>|<version>build_$BUILD_NUMBER</version>|g" pom.xml

      - name: Configure Maven Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: thedudefromci
        run: |
          mkdir -p ~/.m2
          echo "<settings><servers><server><id>github</id><username>${USERNAME}</username><password>${GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml
          mvn -B deploy
